---
scrape_configs:
  - job_name: 'snmp'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.7.10  # SNMP device.
        - 192.168.7.11
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.10:9116
